### ISSUE TITLE
chaos-lemur app is not starting 

### ISSUE THREAD

**Issue by amulyas** [strepsirrhini-army/chaos-lemur#4]
I have set no ENV variables yet .. just built it and trying to push app is not able to start 

2015-09-08T13:25:31.91-0700 [API/0]      OUT App instance exited with guid 26875d03-7e74-4f26-9a42-fdcd131c56de payload: {"cc_partition"=>"default", "droplet"=>"26875d03-7e74-4f26-9a42-fdcd131c56de", "version"=>"ae177e77-23b3-4fae-8f65-4ebbe6d07e74", "instance"=>"2d1249f43a1d4de893a3172d4020e4cd", "index"=>0, "reason"=>"CRASHED", "exit_status"=>1, "exit_description"=>"failed to accept connections within health check timeout", "crash_timestamp"=>1441743945}
2015-09-08T13:25:44.69-0700 [App/0]      OUT [CHAOS LEMUR] INFO  Mapped "{[/env/{name:.*}],methods=[GET]}" onto public java.lang.Object org.springframework.boot.actuate.endpoint.mvc.EnvironmentMvcEndpoint.value(java.lang.String)
2015-09-08T13:25:44.69-0700 [App/0]      OUT [CHAOS LEMUR] INFO  Mapped "{[/mappings],methods=[GET]}" onto public java.lang.Object org.springframework.boot.actuate.endpoint.mvc.EndpointMvcAdapter.invoke()
2015-09-08T13:25:44.87-0700 [App/0]      OUT [CHAOS LEMUR] INFO  
2015-09-08T13:25:45.33-0700 [App/0]      OUT [CHAOS LEMUR] INFO  Blacklist: 
2015-09-08T13:25:45.38-0700 [App/0]      OUT [CHAOS LEMUR] WARN  Exception encountered during context initialization - cancelling refresh attempt
2015-09-08T13:25:45.38-0700 [App/0]      OUT 	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:185) ~[spring-beans-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
2015-09-08T13:25:45.38-0700 [App/0]      OUT 	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:299) ~[spring-beans-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
2015-09-08T13:25:45.38-0700 [App/0]      OUT 	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:194) ~[spring-beans-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
2015-09-08T13:25:45.38-0700 [App/0]      OUT 	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:757) ~[spring-context-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
2015-09-08T13:25:45.38-0700 [App/0]      OUT 	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:686) [spring-boot-1.2.5.RELEASE.jar!/:1.2.5.RELEASE]
2015-09-08T13:25:45.38-0700 [App/0]      OUT 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:957) [spring-boot-1.2.5.RELEASE.jar!/:1.2.5.RELEASE]
2015-09-08T13:25:45.38-0700 [App/0]      OUT 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:946) [spring-boot-1.2.5.RELEASE.jar!/:1.2.5.RELEASE]
2015-09-08T13:25:45.38-0700 [App/0]      OUT 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_60-]
2015-09-08T13:25:45.38-0700 [App/0]      OUT 	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:53) [app/:na]
2015-09-08T13:25:45.38-0700 [App/0]      OUT 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:942) ~[spring-beans-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
2015-09-08T13:25:45.38-0700 [App/0]      OUT 	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:813) ~[spring-beans-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
2015-09-08T13:25:45.38-0700 [App/0]      OUT 	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:741) ~[spring-beans-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
2015-09-08T13:25:45.41-0700 [App/0]      OUT [CHAOS LEMUR] ERROR Application startup failed
2015-09-08T13:25:45.41-0700 [App/0]      OUT org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'destroyer' defined in file [/home/vcap/app/io/pivotal/strepsirrhini/chaoslemur/Destroyer.class]: Unsatisfied dependency expressed through constructor argument with index 3 of type [io.pivotal.strepsirrhini.chaoslemur.infrastructure.Infrastructure]: : No qualifying bean of type [io.pivotal.strepsirrhini.chaoslemur.infrastructure.Infrastructure] found for dependency: expected at least 1 bean which qualifies as autowire candidate for this dependency. Dependency annotations: {}; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type [io.pivotal.strepsirrhini.chaoslemur.infrastructure.Infrastructure] found for dependency: expected at least 1 bean which qualifies as autowire candidate for this dependency. Dependency annotations: {}

**Comment by amulyas** [comment]
setting up ENV variables fixed it

**Comment by twoseat** [comment]
Glad to hear this worked out for you. Do you think the readme is unclear on this, and if so do you have any suggestions for how to improve it? It's difficult to make all the essential information stand out, but I'm keen to avoid anyone losing any time as you did.

**Comment by matthewcosgrove** [comment]
You should update the docs to say something along the lines of

cf push --no-start
cf set-env MANDATORY_PARAM_1 VALUE1
cf set-env MANDATORY_PARAM_2 VALUE2
etc
cf start
